services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: milano_db
      POSTGRES_USER: milano_user
      POSTGRES_PASSWORD: milano_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  rabbitmq:
    image: rabbitmq:latest
    environment:
      RABBITMQ_DEFAULT_USER: milano_user
      RABBITMQ_DEFAULT_PASS: milano_pass
    ports:
      - "5672:5672"
      - "15672:15672"   # panel web de RabbitMQ
    restart: always

volumes:
  postgres_data:
